### ISSUE TITLE
can not install pod

### ISSUE THREAD

**Issue by mohsinalimat** [samnung/RKCalendarLink#1]
can not install pod file...?

ind504:~  cd /Users/Desktop/RKCalendarLink-master/Example 
ind504:Example abc$ pod install
Analyzing dependencies

**Comment by samnung** [comment]
What's the problem? Pods are included in repo

**Comment by mohsinalimat** [comment]
it is stuck in Analyzing dependencies.....

**Comment by samnung** [comment]
Just tried on my computer, it is working.
What version of CocoaPods do you have?

**Comment by mohsinalimat** [comment]
latest one i have downloaded

**Comment by mohsinalimat** [comment]
i install CocoaPods 0.35 version

**Comment by samnung** [comment]
For the first time it must download all specifications. But it should not just stuck while resolving dependencies

**Comment by mohsinalimat** [comment]
ok you mean your code pod problem ok?

**Comment by samnung** [comment]
I mean specifications for all Pods.

That is strange. Try to cancel it with Ctrl+C and run `pod setup` and then again `pod install`

**Comment by mohsinalimat** [comment]
ind504:~ abc$ cd /Users/Desktop/RKCalendarLink-master/Example 
ind504:Example abc$ pod setup
Setting up CocoaPods master repo

i wrote above things but i am not getting...
